name: Docker Image Action for ghcr.io

on:
  push:
    branches:
      - main

env:
  REPO: mobot
  IMAGE: ${{ github.repository_owner }}/${{ env.REPO }}
  VERSION: 2.0.7

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v3.0.0

      - name: Setup Buildx Environment
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to the Github Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PASS }}

      - name: Remove old Testing Container
        uses: ArchieAtkinson/remove-dockertag-action@v0.0
        with:
          tag_name: testing
          github_token: ${{ secrets.GH_PASS }}

      - name: Build and Push new Testing Image
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ env.IMAGE }}:${{ env.VERSION }},ghcr.io/${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE }}:latest
          cache-to: type=inline

      - name: Cleanup Untagged Images
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: ${{ env.REPO }}
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
