name: Docker Image Action for ghcr.io

on:
  push:
    branches:
      - main

env:
  OWNER: ${{ github.repository_owner }}
  IMAGE: mobot
  VERSION: 2.0.7

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Github Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PASS }}

      - name: Build and Push new Testing Image
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.VERSION }},ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:latest

